### ISSUE TITLE
boost-Python issue with Python 3.11

### ISSUE THREAD

**Issue by jcarpent** [conda-forge/boost-feedstock#155]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Dear package managers,

As reported in https://github.com/conda-forge/eigenpy-feedstock/pull/100#issuecomment-1294979634, we currently have some known issues with boost-python and Python 3.11 regarding the support of enum types reported in this issue https://github.com/boostorg/python/pull/385.
Would it be possible to patch the latest release of boost-python with the fix provided in https://github.com/boostorg/python/pull/385?

Thanks in advance for your help and for your great efforts you put in conda,
Best,

Justin

### Installed packages

```shell
None
```

### Environment info

```shell
None
```

**Comment by jakirkham** [comment]
Thanks for the report. Yes we can. Could you please send a PR to the `v1.78.x` branch adding that patch?

**Comment by jcarpent** [comment]
Yes, sure. I will do that now.

**Comment by jakirkham** [comment]
This has been included in recent packages builds of `boost` 1.78.0 and 1.80.0
