### ISSUE TITLE
Setting Python version with conda-forge boost 

### ISSUE THREAD

**Issue by rlovell3** [conda-forge/boost-feedstock#165]
### Comment:

I've been pulling my hair out trying to build (Boost 1.82.0 version) boost.python in a conda environment running Python3.11.  I've successfully built the boost.python.so libraries, but a subsequent compile of a c++ library using the correct Boost.Python includes and linker (from my Boost.Python build, which I've isolated in a ~/test_dir)  results in abstract symbols being populated into the compiled c++ library.  The library is completely unuseable.  This happens even when compiling the simple "hello world" example directly from the Boost docs.

Today I discovered the conda-forge libraries for installing boost and boost.python into a conda env, but my big question is how do those libraries match up with whatever particular flavor of Python I might be using in that specific conda env?  For example, I create a conda env with Python3.11, and want to build boost 1.82.0.  What conda-forge files should I install?  What if I want to run the Boost Python files in a different env running Python 3.7?   Thanks.

**Comment by h-vetinari** [comment]
> For example, I create a conda env with Python3.11, and want to build boost 1.82.0

You don't need to build it, as we have installable packages for this available. You simply need to do:
```
conda install -c conda-forge python=3.11 libboost-python-devel=1.82.0
```

**Comment by h-vetinari** [comment]
Closing this as fixed.
