### ISSUE TITLE
boost/assert.hpp Missing

### ISSUE THREAD

**Issue by ax3l** [conda-forge/boost-feedstock#188]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

After installing all packages, I still cannot find a `boost/assert.hpp` in the conda-forge install.

Usually, this file is part of the default boost headers that are installed.

### Installed packages

`conda list`:

...
  boost                          1.82.0        h781c19f_6                 conda-forge
  boost-cpp                      1.82.0        h44aadfe_6                 conda-forge
  libboost                       1.82.0        h6fcfa73_6                 conda-forge
  libboost-devel                 1.82.0        h00ab1b0_6                 conda-forge
  libboost-headers               1.82.0        ha770c72_6                 conda-forge
  libboost-python                1.82.0        py311h92ebd52_6            conda-forge
  libboost-python-devel          1.82.0        py311h781c19f_6            conda-forge
...
```


### Environment info

`conda info`:

...
            environment : warpx-openmp-dev (active)
           env location : /home/axel/micromamba/envs/warpx-openmp-dev
      user config files : /home/axel/.mambarc
 populated config files : 
       libmamba version : 1.3.1
     micromamba version : 1.3.1
           curl version : libcurl/7.87.0 OpenSSL/3.0.8 zlib/1.2.13 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=6.2.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64
                          __cuda=12.3=0
               channels : 
       base environment : /home/axel/micromamba
               platform : linux-64
```

**Comment by h-vetinari** [comment]
I'm not sure where you're pointing your include path, but the artefact contains that header, as you can check e.g. [here](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Flibboost-headers-1.82.0-ha770c72_6.conda)

**Comment by ax3l** [comment]
Problem solved with
```
  libboost-headers               1.84.0        ha770c72_0                 conda-forge
```
:)
