### ISSUE TITLE
Boost system and filesystem

### ISSUE THREAD

**Issue by glormph** [conda-forge/boost-feedstock#19]
Hi maintainers,
I'm running into trouble when compiling something for bioconda which depends on boost 1.57.0.  cmake complains boost-filesystem and boost-system are missing.

Since the original outside-conda compile script contains `--with-system` and `--with-filesystem` passed to bjam (b2), I wondered if it was a good idea to add those to this compile also, or that there may be another package for that.

**Comment by ccordoba12** [comment]
Please open a pull request to do that, and don't forget to bump the build number of the recipe :-)

**Comment by glormph** [comment]
Thanks! I'll test a bit first, but had to check if there were any a priori issues.

**Comment by jschueller** [comment]
that's useless since all sublibs are built by default ; you can see we check whether all libs are threre including filesystem and system in the meta.yaml

**Comment by glormph** [comment]
You're right. Wonder why cmake complains. If i specify the --with flags the other sublibs are not built at all (but cmake does find them then). Bad idea I guess.

**Comment by jakirkham** [comment]
Should add this feedstock started off with Boost 1.60.0. So I don't think we actually have a package for an earlier version (e.g. 1.57.0). Is this coming from `defaults`? 😕

In any event, we don't use these arguments, but we do test that every Boost library was built by using file checks. So if one of these is missing, the build will fail and not deploy the package.

**Comment by glormph** [comment]
That seems to be it, if I build 1.57.0 (from `defaults`) I get only .so libraries but no static .a ones. If I build the latest available 1.62 from `conda-forge` (or build the 1.57 by hand using the build.sh in this recipe) I do get them (and it works). Thanks for the quick replies!
