### ISSUE TITLE
Removing `gcc` package

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/boost-feedstock#2]
We now have a C++11 capable `gcc` compiler in the docker image. It would be nice if you could do the following to try this.

1. Fork this repo.
2. Create a new branch
3. Remove `gcc` and `libgcc`.
4. Add, commit, push to your fork.
5. Open a PR to remove them.
6. Note in the PR that this issue is fixed by it.

Please ping me when you have done these things.

**Comment by ccordoba12** [comment]
@jakirkham, what gcc version comes now in the docker image?

Please remember that the compilation problem is unrelated to gcc and C++11 support. It has to do with the specific gcc version that comes with CentOS 6 (i.e. gcc 4.4).

As far as I know, C++11 support is not necessary to compile Boost :-)

**Comment by jakirkham** [comment]
It uses devtoolset-2 now so it has the same GLIBC guarantees as the system compiler.

**Comment by msarahan** [comment]
Which is gcc 4.8, @ccordoba12.  Glibc is something like 2.14.

**Comment by jakirkham** [comment]
Actually `glibc` turns out to be 2.12. To be precise, `gcc` is 4.8.2

**Comment by jakirkham** [comment]
Worked nicely. So this will now build without the `gcc` package from here out.

**Comment by jakirkham** [comment]
All packages built and released.
