### ISSUE TITLE
1.86 Migration: RTTI Flag Changes?

### ISSUE THREAD

**Issue by ax3l** [conda-forge/boost-feedstock#218]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In https://github.com/conda-forge/warpx-feedstock/pull/88, I saw that [RTTI issues](https://en.wikipedia.org/wiki/Run-time_type_information) appeared with the 1.86 Boost package rollout.

Are there some unintentional changes to RTTI flags (passed down in CMake link interfaces to dependent projects?) or so with this release?

### Installed packages

See https://github.com/conda-forge/warpx-feedstock/pull/88

### Environment info

See https://github.com/conda-forge/warpx-feedstock/blob/main/recipe/meta.yaml

**Comment by h-vetinari** [comment]
No conscious change from the packaging side - perhaps upstream boost changed/removed/broked something?

**Comment by ax3l** [comment]
I think this was a fluke from the parallel update of the compilers or so. Now it's gone after I  rebuilt all dependencies with the latest conda-forge compiler bump :tada:

**Comment by bluescarni** [comment]
Hello @h-vetinari and @ax3l !

I think I am also seeing RTTI-related issues on Boost. The problem on my side is that, after the recent update of ``cxx-compiler`` from clang 16 to 17, on OSX I am suddenly seeing messages like these on the CI of my projects:

https://github.com/bluescarni/heyoka/actions/runs/10774833753/job/29877863729#step:3:3874

As far as I can tell, the only thing that changed with respect to the last successful run of the CI 5 days ago, is the clang update.

**Comment by bluescarni** [comment]
> Hello @h-vetinari and @ax3l !
> 
> I think I am also seeing RTTI-related issues on Boost. The problem on my side is that, after the recent update of `cxx-compiler` from clang 16 to 17, on OSX I am suddenly seeing messages like these on the CI of my projects:
> 
> https://github.com/bluescarni/heyoka/actions/runs/10774833753/job/29877863729#step:3:3874
> 
> As far as I can tell, the only thing that changed with respect to the last successful run of the CI 5 days ago, is the clang update.

I should probably specify that the ``std::bad_cast`` exceptions are coming from test cases which are using Boost.Serialization to (de)serialize derived classes via pointer to base (this is where the RTTI connection becomes relevant I think).

**Comment by bluescarni** [comment]
> > Hello @h-vetinari and @ax3l !
> > I think I am also seeing RTTI-related issues on Boost. The problem on my side is that, after the recent update of `cxx-compiler` from clang 16 to 17, on OSX I am suddenly seeing messages like these on the CI of my projects:
> > https://github.com/bluescarni/heyoka/actions/runs/10774833753/job/29877863729#step:3:3874
> > As far as I can tell, the only thing that changed with respect to the last successful run of the CI 5 days ago, is the clang update.
> 
> I should probably specify that the `std::bad_cast` exceptions are coming from test cases which are using Boost.Serialization to (de)serialize derived classes via pointer to base (this is where the RTTI connection becomes relevant I think).

I can confirm that pinning ``cxx-compiler<1.8`` fixes the ``std::bad_cast`` exceptions on my CI runs.

@h-vetinari should I open a new issue about this?

**Comment by h-vetinari** [comment]
> @h-vetinari should I open a new issue about this?

Sure, new issues are always more visible than using already closed ones. Sounds though like you might be running into some incompatibility that's being surfaced by llvm 17, which llvm 16 maybe was more lenient on...
