### ISSUE TITLE
Boost and MPI

### ISSUE THREAD

**Issue by gidiko** [conda-forge/boost-feedstock#22]
How hard would it be to include MPI support? Any plans for this? Or do you think this should better be done with a "split", i.e. a seperate `boost-mpi` package?

Currently we are putting MPI in our boost recipe (for linux only) as in 
https://github.com/xdata-skylark/libskylark/tree/master/conda/boost 
but obviously we would love to be able to just point to the "official" conda-forge package(s) for the dependencies :)

**Comment by jschueller** [comment]
you can always propose a patch

**Comment by ccordoba12** [comment]
I think it's better to add it in a different package, but it's probably better to wait until something is decided about the split of boost-python from this package (to avoid a cumbersome dependency on Python for C++ only libraries/packages that depend on Boost).

**Comment by jakirkham** [comment]
So we have split Boost from Boost.Python, probably a good time to revive this if there is still interest. Would agree with @ccordoba12 that a separate Boost package is probably appropriate here.

**Comment by dolfim** [comment]
I'm also interested in ```boost-mpi```. With or without python?

For my projects the python bindings would be useful.

**Comment by jackpap** [comment]
Hi, 
Having boost-mpi packages would definitely be useful. I guess they would depend on the mpi version in the environment ? 
I wouldn't mind contributing this if someone shows me how..

**Comment by jakirkham** [comment]
These live in this feedstock

https://github.com/conda-forge/libboost-mpi-feedstock/tree/main/recipe
