### ISSUE TITLE
System layout for windows

### ISSUE THREAD

**Issue by isuruf** [conda-forge/boost-feedstock#25]
Since conda has vc features, it's fine to have system layout instead of appending the compiler version in the dll names.

(One advantage would be that cmake's FindBoost.cmake script will be able to find newer boost libraries without requiring patches like, conda-forge/cmake-feedstock#29)

**Comment by jakirkham** [comment]
Should this be moved to [boost-cpp]( http://github.com/conda-forge/boost-cpp-feedstock )?

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/boost-cpp-feedstock #8](https://github.com/conda-forge/boost-cpp-feedstock/issues/8) via [**ZenHub**](https://www.zenhub.com/)
