### ISSUE TITLE
Boost Numpy missing

### ISSUE THREAD

**Issue by dolfim** [conda-forge/boost-feedstock#28]
Boost 1.63.0 introduced new Boost Numpy bindings. There are not built here, I guess because numpy is not found.

What about including numpy as a dependency?

**Comment by ccordoba12** [comment]
@isuruf, @jschueller, what do you say?

**Comment by isuruf** [comment]
I'm fine with it.
We can do it once https://github.com/conda-forge/boost-feedstock/pull/27 is in which in turn is dependent on https://github.com/conda-forge/conda-smithy/pull/419

**Comment by jakirkham** [comment]
Also agree with @isuruf. Let's finish up the restructuring of Boost.

**Comment by isuruf** [comment]
#27 will also help with CircleCI. We are at > 1 hour build time and building against 2 numpy versions will make it > 2 hour and CircleCI will timeout.

**Comment by jakirkham** [comment]
Though I should add that we dropped support for NumPy 1.10 recently. So we currently are only building 1 version of NumPy (1.11). Though NumPy devs were talking about release 1.12 as earlier as this weekend. So we will be back to 2 versions of NumPy before long (namely 1.11 and 1.12).

**Comment by jakirkham** [comment]
So we just finished splitting Boost from Boost.Python. We are in good shape for adding NumPy support. Would you be interested in doing a PR, @dolfim?

**Comment by dolfim** [comment]
sure, I will do it in the next days

**Comment by dolfim** [comment]
It is done in #32. Locally it seems to generate the ```boost_numpy``` library.

**Comment by dolfim** [comment]
Fixed in #32.

**Comment by jakirkham** [comment]
Thanks for contributing this, @dolfim.
