### ISSUE TITLE
--with-libraries=graph,filesystem add

### ISSUE THREAD

**Issue by mictadlo** [conda-forge/boost-feedstock#30]
Hi,
Would you be able to add `--with-libraries=graph,filesystem`?

Thank you in advance.

Best wishes,

MIchal

**Comment by jakirkham** [comment]
Moving to [boost-cpp]( http://github.com/conda-forge/boost-cpp-feedstock ) as that is where general Boost stuff is handled now. This feedstock tacks on Boost.Python in addition to everything included in that package.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/boost-cpp-feedstock #5](https://github.com/conda-forge/boost-cpp-feedstock/issues/5) via [**ZenHub**](https://www.zenhub.com/)
