### ISSUE TITLE
Need to package both static and dynamic libraries for components

### ISSUE THREAD

**Issue by wesm** [conda-forge/boost-feedstock#4]
Currently only dynamic libraries are being built. This causes problems in projects with build dependencies on boost requiring the static libraries:

https://circleci.com/gh/conda-forge/staged-recipes/3253

```
CMake Error at /opt/conda/envs/_build/share/cmake-3.5/Modules/FindBoost.cmake:1647 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: /opt/conda/envs/_build/include

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_thread
          boost_unit_test_framework
          boost_date_time
          boost_atomic
```

If no one beats me to it, here is one example of building the complete Boost library stack:

https://github.com/cloudera/native-toolchain/blob/master/source/boost/build.sh

**Comment by jakirkham** [comment]
Agreed. We should be providing them.

Looks like all this would need is a change of `link=shared` -> `link=static,shared` and probably some tests to verify the static libraries are there. Would you be willing to submit a PR?

**Comment by wesm** [comment]
Of course, will that be sufficient in the windows build script, too? Also, I should bump the build number?

**Comment by jakirkham** [comment]
Excellent. Yes, that should be sufficient on Windows too. Yes please bump the build number.

**Comment by jakirkham** [comment]
I downloaded an arbitrary Linux build just for manual verification and it looks like it has those libraries. So you should be good to go, @wesm.

**Comment by wesm** [comment]
thank you @jakirkham!
