### ISSUE TITLE
Consolidate with boost-cpp

### ISSUE THREAD

**Issue by msarahan** [conda-forge/boost-feedstock#53]
The AnacondaRecipes version of this feedstock (https://github.com/anacondarecipes/boost-cpp-feedstock) incorporates boost-python and libboost, as well as "boost" and "boost-cpp" as metapackages.  As part of the unification with defaults, we should discuss how to deprecate this repo and have only one boost feedstock that has the package splitting.

**Comment by jakirkham** [comment]
To avoid having the same discussion twice, would you be alright closing this and continuing in issue ( https://github.com/conda-forge/boost-cpp-feedstock/issues/25 )?

**Comment by msarahan** [comment]
I'd rather not close this issue until a decision has explicitly been made
to either merge recipes or keep them split. I agree that no further
discussion should occur on this particular issue, all discussion should
happen at conda-forge/boost-cpp-feedstock#25 and we should lock this issue
to enforce that.

On Wednesday, April 18, 2018, jakirkham <notifications@github.com> wrote:
> To avoid having the same discussion twice, would you be alright closing
this and continuing in issue ( conda-forge/boost-cpp-feedstock#25 )?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/pvgXQmTZX4-k2EPQMi1hLCzWcZjHyWan7bMP4Nyzh7wEeouQKbynnbWdNyIHF3JAJ1BJ1_pcq57vzzqKjACRVeTwUHa_SALWYKLwRaHQI0gWUjoRWmvca_XnjV7oF0ZuWPLQKRhy85TzsOgu5J3JCLc0cwh-5A=s0-d-e1-ft#https://github.com/notifications/beacon/AACV-fM8LddqIei7c8vn6usi7hfI7TjUks5tp2-fgaJpZM4TYtc-.gif>

**Comment by h-vetinari** [comment]
Closed by #164
