### ISSUE TITLE
Tests are not comprehensive

### ISSUE THREAD

**Issue by 183amir** [conda-forge/boost-feedstock#6]
By taking a quick look at this repository I see that besides checking for existence of files it does not contain any other tests. Is there any make check or similar that can be added here?

**Comment by jakirkham** [comment]
Feel free to submit a PR, @183amir.

One thing to keep mind though. A large portion of Boost is header only. It would be really silly if we are building and running tests on the header only portion. We do that for Eigen (which is all header only) now and I'd like us to stop there. If we add a `make check` style step here, it would be good to have it test the built libraries.

**Comment by jschueller** [comment]
I agree, lets not run more tests here.
