### ISSUE TITLE
boost:1.68: undefined symbol: library depending on boost and build with c++14 

### ISSUE THREAD

**Issue by looooo** [conda-forge/boost-feedstock#66]
Because boost is build with c++17 all dependencies of boost (especially if build against boost.system) must use c++17 too. I guess boost should be more compatible if build with -std=c++14 (But I am not sure)
Maybe it is possible to build with -std=c++14?

**Comment by scopatz** [comment]
For silly historical reasons this is actually boost-python, and boost-cpp is the feedstock that most people think of as boost. Should this be reported to boost-cpp?

**Comment by looooo** [comment]
You are right. Sorry.
