### ISSUE TITLE
Add more file tests

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/boost-feedstock#7]
We just added static libraries. However, our testing of these is a bit incomplete at the moment. For instance, we are not testing Windows static libraries, which start with `libboost_*`. Also, we should make sure we are really testing all the static libraries on the Unix platforms.

**Comment by shadowwalkersb** [comment]
Is [this](https://github.com/GorgonCryoEM/gorgon-hello-feedstock) helpful? Currently, I am trying to debug finding Boost.python on [AppVeyor](https://ci.appveyor.com/project/GorgonCryoEM/gorgon-hello-feedstock/history). If there is interest, I can change the project name to something like `conda-hello` or `conda-smithy-hello` or `conda-forge-hello` or `hello-conda` or `hello-conda-forge` or .... 😛

**Comment by shadowwalkersb** [comment]
@jakirkham , any comments?

**Comment by shadowwalkersb** [comment]
A simple `hello-world` with boost.python can also be used to test other C++ libraries on `conda-forge`. Just listing other projects as dependencies and linking against them would be testing the architecture and VC versions on Windows. I don't think that kind of tests are present at the moment. It should provide testing beyond checking if files exist.

**Comment by jakirkham** [comment]
This is a really old issue. FWICT we have already solved it. So am closing it out. Though additional test patches are welcome.
