### ISSUE TITLE
Add Boost.Python

### ISSUE THREAD

**Issue by Tagar** [conda-forge/boost-feedstock#73]
We're looking to use Boost.Python instead of Cython to access some of our existing C++ libraries.

Would it be possible to add Boost.Python into Anaconda's Boost library ?

https://www.boost.org/doc/libs/1_67_0/libs/python/doc/html/index.html

Thank you!

**Comment by jschueller** [comment]
it's already available, here in conda-forge and in defaults channel

**Comment by Tagar** [comment]
Thank you for prompt response @jschueller 

Found it ! 
https://anaconda.org/anaconda/py-boost

Was looking under a wrong name ..

**Comment by jakirkham** [comment]
That's a different package @Tagar. It's actually in this `boost` package. Please take a closer look.

**Comment by Tagar** [comment]
Gotcha .. we actually use anaconda::boost, which I think is a different than this package? 

```
libboost                  1.65.1               habcd387_4    anaconda
py-boost                  1.65.1           py27hf484d3e_4
```

installing `py-boost` has added `Boost.Python` into what we were missing for the C++/Python interface to work .

Perhaps I still missing something . We just started using Boost from conda, so not sure which package is better in which case. Can you please compare `anaconda::libboost` and `conda-forge::boost`? 

Thanks again.

**Comment by jakirkham** [comment]
Probably best not to use the `anaconda` channel and instead just use `defaults` if that's what you want. `anaconda` AIUI is a sort of copy of `defaults` packages, but I don't know at what regularity it is updated. Anaconda actively maintains `defaults`.

Yes, it is different than this package. Probably you should raises issues with them if there are things to fix. ( https://github.com/AnacondaRecipes )

The `conda-forge::boost` package has the Python parts (similar to `defaults::py-boost`). `conda-forge::boost-cpp` has the C++ bits (similar to `defaults::libboost`).

More generally the `conda-forge` channel is a community maintained channel. Whereas `defaults` is maintained by Anaconda.

**Comment by Tagar** [comment]
Thanks a lot for the detailed explanation @jakirkham
