### ISSUE TITLE
Set -std=c++17 with next boost migration

### ISSUE THREAD

**Issue by saraedum** [conda-forge/boost-feedstock#75]
Currently, our clangxx on macOS builds with `-std=c++14` whereas the `gcc` on Linux builds with `-std=c++17`. We should change macOS to also use `-std=c++17`.

While in general there seem not to be any breaking ABI changes with this switch, boost breaks https://github.com/conda-forge/boost-cpp-feedstock/issues/43.

When boost gets upgraded next time, we likely need a migration anyway. We should use that opportunity to change the CXXFLAGS for clangxx to include `-std=c++17` as boost seems to be the only library affected by these issues.

**Comment by jakirkham** [comment]
Agreed!

cc @isuruf @mingwandroid

**Comment by hmaarrfk** [comment]
can this be closed?

**Comment by sdebionne** [comment]
I think this can be closed since we are now targetting c++20 to build Boost.Cobalt.
